from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from opennamu_forge.application.dto.discussion import TopicCommentDTO


class OtherSettingPort(Protocol):
    def get(self, name: str, *, coverage: str = "", default: str = "") -> str: ...
    def exists(self, name: str, *, coverage: str = "") -> bool: ...
    def upsert(self, name: str, data: str, *, coverage: str = "") -> None: ...
    def ensure(self, name: str, *, default: str = "", coverage: str = "") -> str: ...
    def set_many(self, values: Mapping[str, str], *, coverage: str = "") -> None: ...


class WikiDocumentPort(Protocol):
    def list_titles(
        self,
        *,
        exclude_user_pages: bool = False,
        exclude_file_pages: bool = False,
        exclude_category_pages: bool = False,
    ) -> list[str]: ...
    def list_titles_page(self, *, offset: int = 0, limit: int = 50, prefix: str = "") -> list[str]: ...
    def count_titles(self, *, prefix: str = "") -> int: ...
    def get_data(self, title: str, *, default: str = "") -> str: ...
    def exists_title(self, title: str) -> bool: ...
    def delete_title(self, title: str) -> None: ...
    def rename_title(self, old_title: str, new_title: str) -> None: ...
    def delete_backlinks_by_link(self, link: str) -> None: ...
    def rename_backlink_link(self, old_link: str, new_link: str) -> None: ...
    def insert_no_backlinks_for_title(self, title: str) -> None: ...
    def delete_no_backlinks_for_title(self, title: str) -> None: ...


class DocumentMetaPort(Protocol):
    def get(self, doc_name: str, set_name: str, *, doc_rev: str = "", default: str = "") -> str: ...
    def list_no_link_documents(self, *, offset: int = 0, limit: int = 50) -> list[tuple[str, str]]: ...
    def upsert(self, doc_name: str, set_name: str, set_data: str, *, doc_rev: str = "") -> None: ...
    def delete(self, doc_name: str, set_name: str, *, doc_rev: str = "") -> None: ...
    def get_acl(self, title: str, acl_type: str, *, default: str = "") -> str: ...
    def upsert_acl(self, title: str, acl_type: str, data: str) -> None: ...
    def rename_doc_name(self, old_name: str, new_name: str) -> None: ...
    def delete_doc_name(self, doc_name: str) -> None: ...
    def rename_acl_title(self, old_title: str, new_title: str) -> None: ...
    def delete_acl_title(self, title: str) -> None: ...


class UserSettingPort(Protocol):
    def get(self, user_id: str, name: str, *, default: str = "") -> str: ...
    def exists(self, user_id: str, name: str) -> bool: ...
    def list_data_by_name(self, name: str) -> list[str]: ...
    def upsert(self, user_id: str, name: str, data: str) -> None: ...
    def delete(self, user_id: str, name: str) -> None: ...


class TopicPort(Protocol):
    def get(self, code: str, comment_id: str) -> TopicCommentDTO | None: ...
    def toggle_top(self, code: str, comment_id: str) -> bool: ...
    def toggle_block(self, code: str, comment_id: str) -> bool: ...
    def delete(self, code: str, comment_id: str) -> None: ...
    def exists_recent_discuss_title(self, title: str) -> bool: ...
    def rename_recent_discuss_title(self, old_title: str, new_title: str) -> None: ...
    def count_by_ip(self, ip: str) -> int: ...


class HistoryPort(Protocol):
    def find_send(self, title: str, revision_id: str) -> str | None: ...
    def update_send(self, title: str, revision_id: str, send: str) -> bool: ...
    def exists_title(self, title: str) -> bool: ...
    def latest_revision_id(self, title: str) -> str | None: ...
    def list_revision_ids_ascending(self, title: str) -> list[str]: ...
    def rename_title(self, old_title: str, new_title: str) -> None: ...
    def rename_revision_title_and_id(self, old_title: str, old_revision_id: str, new_title: str, new_revision_id: str) -> None: ...
    def rename_recent_change_title(self, old_title: str, new_title: str) -> None: ...
    def rename_recent_change_title_and_id(self, old_title: str, old_revision_id: str, new_title: str, new_revision_id: str) -> None: ...
    def count_by_ip(self, ip: str) -> int: ...
