from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from opennamu_forge.application.dto.admin import AdminRecordDTO
from opennamu_forge.application.dto.discussion import RecentDiscussDTO, TopicCommentDTO
from opennamu_forge.application.dto.document_meta import AclEntryDTO
from opennamu_forge.application.dto.history import HistoryRecordDTO
from opennamu_forge.application.dto.html_filter import HtmlFilterDTO
from opennamu_forge.application.dto.user_agent import UserAgentDataDTO
from opennamu_forge.application.dto.user_notice import UserNoticeDTO
from opennamu_forge.application.dto.vote import VoteDTO


class OtherSettingPort(Protocol):
    def get(self, name: str, *, coverage: str = "", default: str = "") -> str: ...
    def list_name_data_by_names(self, names: tuple[str, ...], *, coverage: str = "") -> list[tuple[str, str]]: ...
    def exists(self, name: str, *, coverage: str = "") -> bool: ...
    def upsert(self, name: str, data: str, *, coverage: str = "") -> None: ...
    def ensure(self, name: str, *, default: str = "", coverage: str = "") -> str: ...
    def set_many(self, values: Mapping[str, str], *, coverage: str = "") -> None: ...


class AdminPort(Protocol):
    def list_group_names(self) -> list[str]: ...
    def list_group_acls(self, name: str) -> list[str]: ...
    def delete_group(self, name: str) -> None: ...
    def set_group_acls(self, name: str, acl_names: tuple[str, ...]) -> None: ...
    def list_records(self, *, action_prefix: str = "", offset: int = 0, limit: int = 50) -> list[AdminRecordDTO]: ...
    def count_records(self, *, action_prefix: str = "") -> int: ...
    def latest_record_time(self, *, action_prefix: str = "", default: str = "") -> str: ...
    def delete_records_older_than(self, time: str) -> None: ...


class HtmlFilterPort(Protocol):
    def list_by_kind(self, kind: str) -> list[HtmlFilterDTO]: ...
    def list_regex_filters_with_plus(self) -> list[HtmlFilterDTO]: ...
    def exists(self, html: str, kind: str) -> bool: ...
    def get(self, html: str, kind: str) -> HtmlFilterDTO | None: ...
    def get_by_kind_plus(self, kind: str, plus: str) -> HtmlFilterDTO | None: ...
    def get_plus_t(self, html: str, kind: str, *, default: str = "") -> str: ...
    def upsert(self, html: str, kind: str, *, plus: str = "", plus_t: str = "") -> None: ...
    def delete(self, html: str, kind: str) -> None: ...


class BbsPort(Protocol):
    def latest_board_id(self) -> int | None: ...
    def get_setting(self, set_id: str, set_name: str, *, set_code: str = "", default: str = "") -> str: ...
    def get_data(self, set_id: str, set_name: str, set_code: str, *, default: str = "") -> str: ...
    def list_board_names(self) -> list[tuple[str, str]]: ...
    def latest_board_post_date(self, set_id: str) -> str: ...
    def list_pinned_post_refs(self, set_id: str) -> list[tuple[str, str, str]]: ...
    def list_title_post_refs(self, set_id: str) -> list[tuple[str, str]]: ...
    def list_post_refs_by_user(self, user_id: str, *, limit: int = 50) -> list[tuple[str, str]]: ...
    def list_comment_refs_by_user(self, user_id: str, *, limit: int = 50) -> list[tuple[str, str]]: ...
    def list_recent_post_refs(self, *, limit: int = 50) -> list[tuple[str, str, str]]: ...
    def list_data_rows(self, set_id: str, set_code: str) -> list[tuple[str, str, str, str]]: ...
    def count_comments_for_post(self, set_id: str) -> int: ...
    def latest_comment_date_for_post(self, set_id: str) -> str: ...
    def latest_data_code(self, set_id: str, set_name: str) -> int | None: ...
    def add_setting(self, set_id: str, set_name: str, set_data: str, *, set_code: str = "") -> None: ...
    def add_data(self, set_id: str, set_name: str, set_code: str, set_data: str) -> None: ...
    def update_data(self, set_id: str, set_name: str, set_code: str, set_data: str) -> None: ...
    def delete_board(self, set_id: str) -> None: ...
    def delete_post(self, board_id: str, post_id: str) -> None: ...
    def clear_comment(self, set_id: str, set_code: str) -> None: ...
    def is_pinned(self, board_id: str, post_id: str) -> bool: ...
    def delete_data(self, set_id: str, set_name: str, set_code: str) -> None: ...


class BacklinkPort(Protocol):
    def list_distinct_refs(
        self,
        value_column: str,
        filter_column: str,
        filter_value: str,
        *,
        offset: int = 0,
        limit: int = 50,
    ) -> list[tuple[str, str]]: ...
    def list_distinct_refs_case_insensitive(
        self,
        value_column: str,
        filter_column: str,
        filter_value: str,
        *,
        offset: int = 0,
        limit: int = 50,
    ) -> list[tuple[str, str]]: ...
    def list_distinct_links_by_title_type(self, title: str, link_type: str) -> list[str]: ...
    def get_data(self, title: str, link: str, link_type: str, *, default: str = "") -> str: ...
    def exists(self, title: str, link: str, link_type: str) -> bool: ...
    def has_include_title(self, title: str) -> bool: ...
    def get_redirect_for_link(self, link: str) -> tuple[str, str] | None: ...
    def redirect_exists_for_title_or_link(self, value: str) -> bool: ...
    def replace_for_document(self, doc_name: str, rows: list[tuple[str, str, str, str]]) -> None: ...


class WikiDocumentPort(Protocol):
    def list_titles(
        self,
        *,
        exclude_user_pages: bool = False,
        exclude_file_pages: bool = False,
        exclude_category_pages: bool = False,
    ) -> list[str]: ...
    def list_titles_page(self, *, offset: int = 0, limit: int = 50, prefix: str = "") -> list[str]: ...
    def count_titles(self, *, prefix: str = "") -> int: ...
    def count_all_titles(self) -> int: ...
    def get_data(self, title: str, *, default: str = "") -> str: ...
    def find_title(self, title: str) -> str | None: ...
    def find_title_case_insensitive(self, title: str) -> str | None: ...
    def exists_title(self, title: str) -> bool: ...
    def exists_title_prefix(self, prefix: str) -> bool: ...
    def upsert_title(self, title: str, data: str) -> None: ...
    def delete_title(self, title: str) -> None: ...
    def rename_title(self, old_title: str, new_title: str) -> None: ...
    def delete_backlinks_by_link(self, link: str) -> None: ...
    def rename_backlink_link(self, old_link: str, new_link: str) -> None: ...
    def insert_no_backlinks_for_title(self, title: str) -> None: ...
    def delete_no_backlinks_for_title(self, title: str) -> None: ...
    def list_needed_titles(self, *, offset: int = 0, limit: int = 50) -> list[str]: ...


class DocumentMetaPort(Protocol):
    def get(self, doc_name: str, set_name: str, *, doc_rev: str = "", default: str = "") -> str: ...
    def exists(self, doc_name: str, set_name: str, *, doc_rev: str = "") -> bool: ...
    def list_no_link_documents(self, *, offset: int = 0, limit: int = 50) -> list[tuple[str, str]]: ...
    def list_doc_rev_data_by_set_name(self, set_name: str) -> list[tuple[str, str, str]]: ...
    def upsert(self, doc_name: str, set_name: str, set_data: str, *, doc_rev: str = "") -> None: ...
    def delete(self, doc_name: str, set_name: str, *, doc_rev: str = "") -> None: ...
    def update_revision_marker(self, doc_name: str, doc_rev: str) -> None: ...
    def get_acl(self, title: str, acl_type: str, *, default: str = "") -> str: ...
    def acl_title_exists(self, title: str) -> bool: ...
    def list_acl_entries(self, *, offset: int = 0, limit: int = 50) -> list[AclEntryDTO]: ...
    def upsert_acl(self, title: str, acl_type: str, data: str) -> None: ...
    def rename_doc_name(self, old_name: str, new_name: str) -> None: ...
    def delete_doc_name(self, doc_name: str) -> None: ...
    def rename_acl_title(self, old_title: str, new_title: str) -> None: ...
    def delete_acl_title(self, title: str) -> None: ...
    def delete_acl(self, title: str, acl_type: str) -> None: ...


class UserSettingPort(Protocol):
    def get(self, user_id: str, name: str, *, default: str = "") -> str: ...
    def exists(self, user_id: str, name: str) -> bool: ...
    def id_exists(self, user_id: str) -> bool: ...
    def has_any(self) -> bool: ...
    def exists_data(self, user_id: str, name: str, data: str) -> bool: ...
    def data_exists(self, name: str, data: str) -> bool: ...
    def user_data_exists(self, user_id: str, data: str) -> bool: ...
    def find_id_by_name_data(self, name: str, data: str) -> str | None: ...
    def list_ids_by_name_data(self, name: str, data: str) -> list[str]: ...
    def list_data_by_name(self, name: str) -> list[str]: ...
    def list_id_data_by_name(self, name: str) -> list[tuple[str, str]]: ...
    def list_id_data_by_name_excluding_data(self, name: str, excluded_data: str) -> list[tuple[str, str]]: ...
    def list_id_data_by_name_ordered_by_data_desc(self, name: str, *, offset: int = 0, limit: int = 50) -> list[tuple[str, str]]: ...
    def count_by_name(self, user_id: str, name: str) -> int: ...
    def upsert(self, user_id: str, name: str, data: str) -> None: ...
    def add(self, user_id: str, name: str, data: str) -> None: ...
    def delete(self, user_id: str, name: str) -> None: ...
    def delete_data(self, user_id: str, name: str, data: str) -> None: ...
    def update_user_title_checkmark(self, user_id: str) -> None: ...


class UserNoticePort(Protocol):
    def list_by_user(self, user_id: str, *, offset: int = 0, limit: int = 50) -> list[UserNoticeDTO]: ...
    def mark_read(self, user_id: str) -> None: ...
    def delete(self, user_id: str, notice_id: str) -> None: ...
    def delete_all(self, user_id: str) -> None: ...


class UserAgentDataPort(Protocol):
    def count_distinct_ips_by_identity(self, identity_column: str, identity_value: str) -> int: ...
    def count_distinct_ips_by_two_identities(self, first_column: str, first_value: str, second_column: str, second_value: str) -> int: ...
    def list_by_identity(self, identity_column: str, identity_value: str, *, offset: int = 0, limit: int = 50) -> list[UserAgentDataDTO]: ...
    def list_by_two_identities(
        self,
        first_column: str,
        first_value: str,
        second_column: str,
        second_value: str,
        *,
        offset: int = 0,
        limit: int = 50,
    ) -> list[UserAgentDataDTO]: ...
    def list_distinct_values_by_identity(
        self,
        value_column: str,
        identity_column: str,
        identity_value: str,
        *,
        offset: int = 0,
        limit: int = 50,
    ) -> list[str]: ...
    def delete(self, name: str, ip: str, today: str) -> None: ...
    def delete_older_than(self, today: str) -> None: ...
    def add(self, name: str, ip: str, ua: str, today: str, *, sub: str = "") -> None: ...


class RecentBlockPort(Protocol):
    def get_ongoing_end(self, block: str, *, default: str = "") -> str: ...
    def close_ongoing(self, block: str, band: str) -> None: ...
    def close_expired(self, now: str) -> None: ...
    def add_record(self, block: str, end: str, today: str, blocker: str, why: str, band: str, ongoing: str, login: str) -> None: ...


class VotePort(Protocol):
    def latest_vote_id(self) -> int | None: ...
    def add_main(self, name: str, vote_id: str, subject: str, data: str, vote_type: str, acl: str) -> None: ...
    def add_option(self, name: str, vote_id: str, data: str) -> None: ...
    def add_selection(self, vote_id: str, data: str, user: str) -> None: ...
    def list_by_types(self, vote_types: tuple[str, ...], *, offset: int = 0, limit: int = 50) -> list[VoteDTO]: ...
    def get_main(self, vote_id: str) -> VoteDTO | None: ...
    def get_option(self, vote_id: str, name: str, *, default: str = "") -> str: ...
    def has_user_selection(self, vote_id: str, user: str) -> bool: ...
    def list_selection_users(self, vote_id: str, data: str) -> list[str]: ...
    def update_main_type(self, vote_id: str, old_type: str, new_type: str) -> None: ...
    def delete_option(self, vote_id: str, name: str) -> None: ...


class TopicPort(Protocol):
    def get(self, code: str, comment_id: str) -> TopicCommentDTO | None: ...
    def list_by_ip(self, ip: str, *, offset: int = 0, limit: int = 50) -> list[TopicCommentDTO]: ...
    def get_recent_discuss(self, code: str) -> RecentDiscussDTO | None: ...
    def get_thread_setting(self, code: str, name: str, *, default: str = "") -> str: ...
    def latest_topic_code(self) -> int | None: ...
    def latest_comment_id(self, code: str) -> int | None: ...
    def add_comment(self, code: str, comment_id: str, data: str, date: str, ip: str, block: str, *, top: str = "") -> None: ...
    def list_comment_ids_ascending(self, code: str) -> list[str]: ...
    def first_comment_author(self, code: str) -> str | None: ...
    def toggle_top(self, code: str, comment_id: str) -> bool: ...
    def toggle_block(self, code: str, comment_id: str) -> bool: ...
    def delete(self, code: str, comment_id: str) -> None: ...
    def delete_thread(self, code: str) -> None: ...
    def update_recent_discuss_title_subtitle(self, code: str, title: str, subtitle: str) -> None: ...
    def update_recent_discuss_stop(self, code: str, stop: str) -> None: ...
    def update_recent_discuss_agree(self, code: str, agree: str) -> None: ...
    def update_recent_discuss_date(self, code: str, date: str) -> bool: ...
    def add_recent_discuss(self, code: str, title: str, subtitle: str, date: str) -> None: ...
    def update_recent_discuss_acl(self, code: str, acl: str) -> None: ...
    def upsert_thread_setting(self, code: str, name: str, data: str, *, set_id: str = "1") -> None: ...
    def exists_recent_discuss_title(self, title: str) -> bool: ...
    def exists_open_recent_discuss_title(self, title: str) -> bool: ...
    def rename_recent_discuss_title(self, old_title: str, new_title: str) -> None: ...
    def count_by_ip(self, ip: str) -> int: ...
    def latest_date_by_ip(self, ip: str) -> str | None: ...


class HistoryPort(Protocol):
    def find_data(self, title: str, revision_id: str) -> str | None: ...
    def find_send(self, title: str, revision_id: str) -> str | None: ...
    def update_send(self, title: str, revision_id: str, send: str) -> bool: ...
    def is_hidden(self, title: str, revision_id: str) -> bool: ...
    def any_hidden(self, title: str, revision_ids: tuple[str, ...]) -> bool: ...
    def toggle_hidden(self, title: str, revision_id: str) -> bool: ...
    def exists_title(self, title: str) -> bool: ...
    def latest_revision_id(self, title: str) -> str | None: ...
    def earliest_revision_id(self, title: str) -> str | None: ...
    def list_revision_ids_ascending(self, title: str) -> list[str]: ...
    def list_records_by_title(self, title: str, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_records_by_title_type(self, title: str, change_type: str, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_records_by_ip(self, ip: str, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_records_by_ip_type(self, ip: str, change_type: str, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_records(self, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_records_by_type(self, change_type: str, *, offset: int = 0, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def list_recent_change_records_by_type(self, change_type: str, *, limit: int = 50) -> list[HistoryRecordDTO]: ...
    def count_recent_changes_by_type(self, change_type: str) -> int: ...
    def oldest_recent_change_ref_by_type(self, change_type: str) -> tuple[str, str] | None: ...
    def delete_recent_change(self, title: str, revision_id: str, change_type: str) -> None: ...
    def add_recent_change(self, title: str, revision_id: str, date: str, change_type: str) -> None: ...
    def add_history(self, title: str, revision_id: str, data: str, date: str, ip: str, send: str, length: str, change_type: str) -> None: ...
    def delete_revision(self, title: str, revision_id: str) -> None: ...
    def delete_title(self, title: str) -> None: ...
    def delete_by_ip(self, ip: str) -> None: ...
    def list_lengths_by_ip_date_prefix(self, ip: str, date_prefix: str) -> list[str]: ...
    def rename_title(self, old_title: str, new_title: str) -> None: ...
    def rename_revision_title_and_id(self, old_title: str, old_revision_id: str, new_title: str, new_revision_id: str) -> None: ...
    def rename_recent_change_title(self, old_title: str, new_title: str) -> None: ...
    def rename_recent_change_title_and_id(self, old_title: str, old_revision_id: str, new_title: str, new_revision_id: str) -> None: ...
    def count_by_ip(self, ip: str) -> int: ...
    def latest_date_by_ip(self, ip: str) -> str | None: ...
