from __future__ import annotations

from collections.abc import Mapping
from typing import Protocol

from opennamu_forge.application.dto.discussion import TopicCommentDTO


class OtherSettingPort(Protocol):
    def get(self, name: str, *, coverage: str = "", default: str = "") -> str: ...
    def exists(self, name: str, *, coverage: str = "") -> bool: ...
    def upsert(self, name: str, data: str, *, coverage: str = "") -> None: ...
    def ensure(self, name: str, *, default: str = "", coverage: str = "") -> str: ...
    def set_many(self, values: Mapping[str, str], *, coverage: str = "") -> None: ...


class WikiDocumentPort(Protocol):
    def list_titles(
        self,
        *,
        exclude_user_pages: bool = False,
        exclude_file_pages: bool = False,
        exclude_category_pages: bool = False,
    ) -> list[str]: ...
    def list_titles_page(self, *, offset: int = 0, limit: int = 50, prefix: str = "") -> list[str]: ...
    def count_titles(self, *, prefix: str = "") -> int: ...


class DocumentMetaPort(Protocol):
    def get(self, doc_name: str, set_name: str, *, doc_rev: str = "", default: str = "") -> str: ...
    def list_no_link_documents(self, *, offset: int = 0, limit: int = 50) -> list[tuple[str, str]]: ...


class UserSettingPort(Protocol):
    def get(self, user_id: str, name: str, *, default: str = "") -> str: ...
    def list_data_by_name(self, name: str) -> list[str]: ...
    def upsert(self, user_id: str, name: str, data: str) -> None: ...
    def delete(self, user_id: str, name: str) -> None: ...


class TopicPort(Protocol):
    def get(self, code: str, comment_id: str) -> TopicCommentDTO | None: ...
    def toggle_top(self, code: str, comment_id: str) -> bool: ...
    def toggle_block(self, code: str, comment_id: str) -> bool: ...
    def delete(self, code: str, comment_id: str) -> None: ...


class HistoryPort(Protocol):
    def find_send(self, title: str, revision_id: str) -> str | None: ...
    def update_send(self, title: str, revision_id: str, send: str) -> bool: ...
