from __future__ import annotations

from enum import Enum


class SettingKey(str, Enum):
    APPROVAL_QUESTION = "approval_question"
    BBS_COMMENT_HELP = "bbs_comment_help"
    BBS_HELP = "bbs_help"
    BODY = "body"
    BOTTOM_BODY = "bottom_body"
    CHECK_KEY_TEXT = "check_key_text"
    CONTRACT = "contract"
    DOCUMENT_CONTENT_MAX_LENGTH = "document_content_max_length"
    EDIT_HELP = "edit_help"
    EDIT_TIMEOUT = "edit_timeout"
    EMAIL_HAVE = "email_have"
    EMAIL_INSERT_TEXT = "email_insert_text"
    EMAIL_TEXT = "email_text"
    EMAIL_TITLE = "email_title"
    ENCODE = "encode"
    ERROR_401 = "error_401"
    ERROR_404 = "error_404"
    IP_VIEW = "ip_view"
    LINK_CASE_INSENSITIVE = "link_case_insensitive"
    MARKUP = "markup"
    OUTDATED_DOC_WARNING = "outdated_doc_warning"
    OUTDATED_DOC_WARNING_DATE = "outdated_doc_warning_date"
    PASSWORD_MIN_LENGTH = "password_min_length"
    PASSWORD_SEARCH_TEXT = "password_search_text"
    PHRASE_USER_PAGE_ADMIN = "phrase_user_page_admin"
    PHRASE_USER_PAGE_OWNER = "phrase_user_page_owner"
    REDIRECT_TEXT = "redirect_text"
    REG = "reg"
    REQUIRES_APPROVAL = "requires_approval"
    RESET_USER_TEXT = "reset_user_text"
    TOPIC_TEXT = "topic_text"
    UPLOAD = "upload"
    UPLOAD_DEFAULT = "upload_default"
    UPLOAD_HELP = "upload_help"
